# Site settings
title: "Víctor Aguilar"
email: "victor-aguilarsnz@gmail.com"
description: "Senior Software Engineer | Building scalable distributed systems and cloud-native applications"
url: "https://victor-aguilars.github.io"
github_username: "victor-aguilars"
linkedin_username: "víctor-alfredo-aguilar-sánchez"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from build
exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Social media links
social:
  github: "https://github.com/victor-aguilars"
  linkedin: "https://linkedin.com/in/víctor-alfredo-aguilar-sánchez"
  email: "mailto:victor-aguilarsnz@gmail.com"

# SEO settings
author: "Victor Aguilar"
lang: "en_US"