# Site settings
title: "Victor Aguilar"
email: "your.email@example.com"
description: "Web Developer | Building responsive and user-friendly applications"
url: "https://victor.aguilars.github.io"
github_username: "victor.aguilars"
linkedin_username: "victor-aguilar"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from build
exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Social media links
social:
  github: "https://github.com/victor.aguilars"
  linkedin: "https://linkedin.com/in/victor-aguilar"
  email: "mailto:your.email@example.com"

# SEO settings
author: "Victor Aguilar"
lang: "en_US"